== Docker

=== Introduction

==== Docker

Docker est une plateforme ouverte pour développeurs et administrateurs système. Docker permet de construire, livrer et exécuter des applications distribuées aussi bien sur des machines physiques, des machines virtuelles, le cloud...

==== Docker vs VM

Docker est une technologie de *conteneurisation* qui permet de créer des conteneurs légers et portables pour les applications logicielles. Les *conteneurs* sont des environnements isolés qui contiennent tout ce dont une application a besoin pour fonctionner, y compris le code, les bibliothèques, les outils et les fichiers système.

Les *machines virtuelles* (VM) sont des environnements d'exécution isolés qui contiennent un système d'exploitation complet. Les VMs sont plus lourdes que les conteneurs car elles contiennent un système d'exploitation complet.

Les conteneurs partagent le noyau du système d'exploitation hôte et ne contiennent que les éléments nécessaires à l'exécution de l'application containeurisée. Cela implique que les conteneurs sont plus légers que les VMs et peuvent être démarrés plus rapidement. Cela implique aussi que les conteneurs sont moins isolés que les VMs.

=== Installation

* [Docker Desktop pour Windows](https://docs.docker.com/desktop/setup/install/windows-install/)
** lors de d'installation, assurez-vous d'utiliser WSL2 et non Hyper-V
* L'installation va automatiquement activer/installer certaines fonctionnalités Windows requises
* En cas de problème, vérifiez :
** que la virtualisation est activée dans le BIOS
** que vous avez bien installé/activé WSL2 et Hyper-V
*** https://docs.docker.com/desktop/troubleshoot-and-support/troubleshoot/topics/#virtualization
*** https://learn.microsoft.com/en-us/windows/wsl/install

